Port options to use Context instead of a raw GuildMessageReceivedEvent
Mantaro/MantaroBot pull request #408
Opened 2020-12-28 22:07 UTC by Kodehawa

This also adds support for mention prefix. The porting was necessary to make this work.

Might need more changes and is untested. I need to give this a proper test on all options :)

2020-12-29 21:38 UTC, natanbc requested changes

2020-12-29 21:38 UTC, natanbc commented on src/main/java/net/kodehawa/mantarobot/core/modules/commands/base/Context.java
> +            final var mutable = new LinkedList<>(mentionedUsers);
List#subList()

2020-12-29 21:38 UTC, natanbc commented on src/main/java/net/kodehawa/mantarobot/core/modules/commands/base/Context.java
> +            final var mutable = new LinkedList<>(mentionedMembers);
List#subList

2020-12-29 21:38 UTC, natanbc commented on src/main/java/net/kodehawa/mantarobot/commands/custom/legacy/CustomMessage.java
> +            var mutable = new LinkedList<>(mentionedUsers);
List#subList

2020-12-30 21:18 UTC, Kodehawa commented on src/main/java/net/kodehawa/mantarobot/commands/custom/legacy/CustomMessage.java
> +            var mutable = new LinkedList<>(mentionedUsers);
done

2020-12-30 21:18 UTC, Kodehawa commented on src/main/java/net/kodehawa/mantarobot/core/modules/commands/base/Context.java
> +            final var mutable = new LinkedList<>(mentionedUsers);
done

2020-12-30 21:18 UTC, Kodehawa commented on src/main/java/net/kodehawa/mantarobot/core/modules/commands/base/Context.java
> +            final var mutable = new LinkedList<>(mentionedMembers);
done

2021-01-01 06:39 UTC, merged